# BERT Model Configuration
pretrained_model: 'bert-base-uncased'
num_classes: 4
dropout_rate: 0.1

# Training parameters
learning_rate: 2e-5
adam_epsilon: 1e-8
warmup_steps: 0
max_grad_norm: 1.0
num_epochs: 3
batch_size: 16
save_model: true
model_save_path: 'models/saved/bert_model.pt'