batch_size: 32
bidirectional: true
cell_type: gru
dropout_rate: 0.3
embedding_dim: 300
filter_sizes:
- 2
- 3
- 4
hidden_dim: 512
learning_rate: 0.0005
max_length: 150
model_type: cnn
num_epochs: 5
num_filters: 200
num_layers: 2
vocab_size: 87272
