batch_size: 32
bidirectional: false
cell_type: lstm
dropout_rate: 0.7
embedding_dim: 200
filter_sizes:
- 2
- 4
- 6
hidden_dim: 256
learning_rate: 0.002
max_length: 100
model_type: rnn
num_epochs: 10
num_filters: 50
num_layers: 2
vocab_size: 87272
